### ISSUE TITLE
7 DOF turtlebot arm description

### ISSUE THREAD

**Issue by kimhc6028** [turtlebot/turtlebot_arm#17]
Do you have 7 DOF turtlebot arm urdf file? Or could I make one with your meshes file?

**Comment by corot** [comment]
Not sure what do you mean with a 7DOF turtlebot arm... Can you provide more details? If you mean to stack 3 additional Dynamixel AX-12A servos with the corresponding structural elements, you can easily extend the existing URDF file (reusing existing meshes), but I guess the first two servos won't be able to bear the extra weight.

**Comment by corot** [comment]
Sorry @kimhc6028, I cannot get the point of this issue. Maybe you should post the question in http://answers.ros.org..
