### ISSUE TITLE
robotic arm object tracking ??

### ISSUE THREAD

**Issue by Abduoit** [turtlebot/turtlebot_arm#33]
Hi,

Can Pincher arm track an object by using normal camera or even kinect v1. How the arm can track an object based on color for example ???

**Comment by corot** [comment]
This is clearly a candidate for [ROS answers](https://answers.ros.org). Repository issues are intended to report bugs or propose new features, not to discuss usage.

I promise to answer you there! :v:

**Comment by Abduoit** [comment]
@corot 
thanks for reply 

I already posted same question. You can answer my question in this [link](https://answers.ros.org/question/272202/robotic-arm-object-tracking/)

Thanks in advance
