### ISSUE TITLE
Add kinect calibration for Hydro/Indigo

### ISSUE THREAD

**Issue by mikeferguson** [turtlebot/turtlebot_arm#4]

**Comment by stonier** [comment]
We'll be catkinizing the non-catkin stacks shortly fergs.

**Comment by mikeferguson** [comment]
Daniel, I meant to assign myself on this. I've been pulling turtlebot_arm into the future. I've already updated most of the other packages, moved to MoveIt (since arm_navigation is long gone). But the calibration package needs some attention to actually work.

**Comment by corot** [comment]
This package is outdated and cannot work on hydro/indigo, so more than catkinize we need an entirely new version.

**Comment by corot** [comment]
OK for Indigo. Sorry for Hydro, but I don't plan to maintain a Hydro branch at all.

**Comment by mikeferguson** [comment]
Just a thought, given how much you've cleaned up the other naming, it might make sense to rename the package to turtlebot_arm_kinect_calibration

**Comment by corot** [comment]
:+1: 
btw, I'm gonna release the repo on indigo as version 0.3 and change maintainer to myself :cold_sweat:, if you have no inconvenient.
