### ISSUE TITLE
Release for Hydro?

### ISSUE THREAD

**Issue by bit-pirate** [turtlebot/turtlebot_arm#9]
@mikeferguson do you plan to release turtlebot_arm into Hydro?

**Comment by mikeferguson** [comment]
Maybe, but things are not actually fully functional yet (they basically compile on the desktop, I'm sure there are dependencies missing that will break it on the farm, and then the calibration/demos really aren't fully working or tested yet)

**Comment by corot** [comment]
Well... never happened. Maybe for indigo... :pray:
